[package]
name = "bft_interp"
version = "0.1.0"
authors = ["John Ward <john@johnward.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bft_types = { version = "0.1.0", path = "../bft_types" }
